phases:

  build:

    commands:

      - "echo Build started on `date`"

      - "echo Building the Docker image..."

      - "docker build -t web ."

      - "docker tag web:latest 980424229685.dkr.ecr.us-east-1.amazonaws.com/mywebserver:latest"

  post_build:

    commands:

      - "echo Build completed on `date`"

      - "echo Pushing the Docker image..."

      - "docker push 980424229685.dkr.ecr.us-east-1.amazonaws.com/mywebserver:latest"
      
      - printf '[{"name":"mywebserver","imageUri":"%s"}]' 980424229685.dkr.ecr.us-east-1.amazonaws.com/mywebserver:latest > imagedefinitions.json

artifacts:
    files:
      - imagedefinitions.json
    pre_build:
     commands:

      - "echo Logging in to Amazon ECR..."

      - "$(aws ecr get-login --region us-east-1)"

version: 0.1
